name: Close inactive issues
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Minute, Hour, Day, Month, Weekの純
    - cron: "30 1 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v3
        with:
          days-before-issue-stale: 14
          days-before-issue-close: 7
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 14 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 7 days since being marked as stale."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

# Ref
# https://docs.github.com/ja/actions/managing-issues-and-pull-requests/closing-inactive-issues